### PR TITLE
Action, AttachmentField, Edited and Reply conform to Codable

### PR DESCRIPTION
**Pull request by RomanPodymov**
Hello.
In this pull request I started the implementation of the feature described in #122. Please comment if I started it correctly.

### CODE REVIEW

**Comment by pvzig** [comment]
Thanks for the contribution and apologies for the slow response! I will take a look this weekend.

**Comment by pvzig** [comment]
This looks great, thanks for adding tests!

**Comment by RomanPodymov** [comment]
Hello @pvzig 
In such case I will continue with #122.

**Comment by pvzig** [comment]
That would be great 😁

**Pull request merged**
