### PR TITLE
Feature/history object

### PR DESCRIPTION
**Pull request by pvzig**
- Add History object

### CODE REVIEW

**Comment by hamin** [comment]
@pvzig @muratayusuke this is awesome!!!

**Comment by hamin** [comment]
@pvzig lots of great stuff since the last version bump. You think it would be cool to bump the version again?

**Comment by pvzig** [comment]
@hamin Done, check it out here: https://github.com/pvzig/SlackKit/releases/tag/0.9.9

Pushing an update to the CocoaPod now.

**Comment by hamin** [comment]
thank you :)

**Pull request merged**
