### PR TITLE
Add reference to client to channel

### PR DESCRIPTION
**Pull request by muratayusuke**

### CODE REVIEW

**Comment by pvzig** [comment]
@muratayusuke What functionality are you trying to unlock with this PR? There has to be a better way than adding a reference to the Client to the Channel model type.

**Comment by muratayusuke** [comment]
@pvzig I'm developing app handling channels of multiple teams ( http://apple.co/1Rm2dwI ).

Currently, I'm using new struct that include client and channel in order to find "which client have this channel?".

But actually I just need reference to parent client in channel.

I think every app using multiple `Client` need this reference :)

**Comment by pvzig** [comment]
I feel pretty strongly about keeping the Client logic and the basic types separated, so I'm trying to think through good ways to enable this functionality. If you're referencing the channels on their respective clients, you should be able to tell them apart using the Team ID: `client.team?.id`. If you're adding them together in a collection, maybe something like adding a `teamID` property to `Channel` would work?

P.S. I've seen your app, very cool!

**Comment by muratayusuke** [comment]
I see, I'm going to really opposite side in [another branch](https://github.com/muratayusuke/SlackKit/commits/feature/rx) especially [this function](https://github.com/muratayusuke/SlackKit/commit/678e9073b604b3a205cb43ce7e013467bb749aab#diff-47cfd6a385989638b775777e7064c739R15)... (I think rx functions should be separated to another library like `SlackKit+Rx` in the future, anyway)

`teamID` property in `Channel` seems to work well, but I'll still need wrapper class of `Channel` type or a kind of utility function to find client from `teamID` easily.

I'm happy if I can write:

```
self.channel.rx_history()
    .map { history in
        return history.messages
    }
    .bindTo(self.tableView.rx_itemsWithCellIdentifier(...)) {
        ...
    }
```

in ViewController for each channel with `rx_history()` above.

Do you have any idea of nice place to put these functions instead of `Channel` itself?

Or should be written only in each app?

> P.S. I've seen your app, very cool!

Thank you!!

**Comment by pvzig** [comment]
I think with the direction you're going a separate `RxSlackKit` library that extends SlackKit is a great idea. Gonna close this for now.

**Pull request closed without merging**
